"""
§Fase 25.f — CTranspiler test suite + drift gate vs RustTranspiler.

The CTranspiler is the C-source emitter for AXON compute blocks
(parallel to RustTranspiler). These tests verify:

  1. Pure correctness — emitted C source matches the documented shape
  2. Operator whitelist — only `{+, -, *, /}` accepted
  3. Identifier validation — unknown idents raise ValueError
  4. Source hash determinism — same input → same hash
  5. NativeCompiler integration — Tier-2 compilation delegates to
     CTranspiler instead of the legacy inline transpiler
  6. Drift gate vs RustTranspiler — both transpilers MUST accept and
     reject the same set of inputs (semantic parity at the DSL level)
  7. Mathematical-purity boundary — DSL grammar rejects anything that
     would compromise PIX information-theoretic guarantees, MDN
     locality, or algebraic-effects discipline (founder ratification
     2026-05-08)
"""

from __future__ import annotations

import sys

import pytest

from axon.runtime.c_transpiler import CTranspileResult, CTranspiler
from axon.runtime.native_compiler import NativeCompiler
from axon.runtime.rust_transpiler import RustTranspiler


# ════════════════════════════════════════════════════════════════════
#  Pure CTranspiler correctness
# ════════════════════════════════════════════════════════════════════


class TestCTranspilerCorrectness:
    """Verify C source generation from compute logic DSL."""

    def test_simple_addition_returns_result(self):
        t = CTranspiler()
        result = t.transpile(
            "let result = a + b\nreturn result",
            "Add",
            ["a", "b"],
        )
        assert isinstance(result, CTranspileResult)
        assert result.fn_name == "axon_compute_Add"
        assert "double a" in result.c_source
        assert "double b" in result.c_source
        assert "return result" in result.c_source

    def test_function_signature_returns_double(self):
        t = CTranspiler()
        result = t.transpile("return x", "Identity", ["x"])
        assert "double axon_compute_Identity" in result.c_source

    def test_export_macro_platform_specific(self):
        t = CTranspiler()
        result = t.transpile("return x", "Identity", ["x"])
        if sys.platform == "win32":
            assert "__declspec(dllexport)" in result.c_source
        else:
            assert '__attribute__((visibility("default")))' in result.c_source

    def test_void_param_list_when_no_params(self):
        # C requires `void` for an empty parameter list (NOT empty
        # parens, which are K&R-style and removed in C23).
        t = CTranspiler()
        result = t.transpile("return 1", "Constant", [])
        assert "(void)" in result.c_source

    def test_let_bindings_emit_double_declarations(self):
        t = CTranspiler()
        result = t.transpile(
            "let tax = amount * rate\nlet total = amount + tax\nreturn total",
            "CalculateTax",
            ["amount", "rate"],
        )
        assert "double tax = amount * rate" in result.c_source
        assert "double total = amount + tax" in result.c_source

    def test_integer_literals_get_double_suffix(self):
        # `5 / 2` in C is integer division (= 2). The transpiler MUST
        # emit `5.0 / 2.0` so the operation stays floating-point.
        t = CTranspiler()
        result = t.transpile("return 5 / 2", "HalfFive", [])
        assert "5.0" in result.c_source
        assert "2.0" in result.c_source

    def test_float_literals_pass_through_unchanged(self):
        t = CTranspiler()
        result = t.transpile("return 1.5", "Half", [])
        assert "1.5" in result.c_source

    def test_source_hash_deterministic(self):
        t = CTranspiler()
        r1 = t.transpile("return a + b", "Add", ["a", "b"])
        r2 = t.transpile("return a + b", "Add", ["a", "b"])
        assert r1.source_hash == r2.source_hash

    def test_different_logic_different_hash(self):
        t = CTranspiler()
        r1 = t.transpile("return a + b", "Add", ["a", "b"])
        r2 = t.transpile("return a * b", "Mul", ["a", "b"])
        assert r1.source_hash != r2.source_hash

    def test_same_logic_different_fn_name_same_hash(self):
        # The hash is over the LOGIC source only — fn_name is metadata
        # for the cache key, not part of the deterministic morphism.
        t = CTranspiler()
        r1 = t.transpile("return a", "FnOne", ["a"])
        r2 = t.transpile("return a", "FnTwo", ["a"])
        assert r1.source_hash == r2.source_hash

    def test_param_names_preserved_in_result(self):
        t = CTranspiler()
        result = t.transpile("return a + b", "Add", ["a", "b"])
        assert result.param_names == ("a", "b")

    def test_source_includes_provenance_comment(self):
        t = CTranspiler()
        result = t.transpile("return x", "X", ["x"])
        assert "Auto-generated by AXON C Transpiler" in result.c_source
        assert "Source hash:" in result.c_source

    def test_source_includes_pillar_boundary_comment(self):
        # Mathematical-purity boundary documented INLINE in the emitted
        # source — anyone reading the .c file sees the founder rule.
        t = CTranspiler()
        result = t.transpile("return x", "X", ["x"])
        assert "no PIX / MDN / effects" in result.c_source

    def test_complex_arithmetic_transpiles(self):
        t = CTranspiler()
        result = t.transpile(
            "let s = a + b\nlet d = a - b\nlet p = s * d\nreturn p",
            "DiffOfSquares",
            ["a", "b"],
        )
        assert "axon_compute_DiffOfSquares" in result.fn_name
        assert "double s = a + b" in result.c_source
        assert "double d = a - b" in result.c_source
        assert "double p = s * d" in result.c_source

    def test_parens_in_expression_preserved(self):
        t = CTranspiler()
        result = t.transpile(
            "return ( a + b ) * c",
            "Weighted",
            ["a", "b", "c"],
        )
        assert "(" in result.c_source
        assert ")" in result.c_source
        assert "* c" in result.c_source


# ════════════════════════════════════════════════════════════════════
#  Validation — operator whitelist + identifier safety
# ════════════════════════════════════════════════════════════════════


class TestCTranspilerValidation:
    """The DSL must reject anything outside its formal grammar."""

    def test_empty_logic_source_raises(self):
        t = CTranspiler()
        with pytest.raises(ValueError, match="Empty logic_source"):
            t.transpile("", "Empty", [])

    def test_missing_return_raises(self):
        t = CTranspiler()
        with pytest.raises(ValueError, match="must contain a 'return'"):
            t.transpile("let x = 1", "NoReturn", [])

    def test_unsupported_statement_raises(self):
        t = CTranspiler()
        with pytest.raises(ValueError, match="Unsupported compute DSL"):
            t.transpile("if a > b: return a", "IfStmt", ["a", "b"])

    def test_unknown_identifier_raises(self):
        t = CTranspiler()
        with pytest.raises(ValueError, match="Unknown identifier"):
            t.transpile("return mystery_var", "Unknown", ["a"])

    def test_disallowed_operator_treated_as_identifier(self):
        # Bitwise operators are NOT in the whitelist; the tokeniser
        # splits on `&` only because it's not in [+\-*/()] — so `&`
        # falls through to the identifier branch and fails.
        t = CTranspiler()
        with pytest.raises(ValueError):
            t.transpile("return a & b", "Bitwise", ["a", "b"])

    def test_function_call_rejected(self):
        # `sqrt(x)` would require `sqrt` to be a known identifier —
        # which it isn't, since the whitelist is just params + locals.
        t = CTranspiler()
        with pytest.raises(ValueError, match="Unknown identifier"):
            t.transpile("return sqrt(x)", "Sqrt", ["x"])

    def test_identifier_outside_params_or_locals_rejected(self):
        # Even if it's a valid C identifier, only params + previously-
        # bound locals are allowed.
        t = CTranspiler()
        with pytest.raises(ValueError, match="Unknown identifier"):
            t.transpile("return undeclared", "Undeclared", ["a"])

    def test_preprocessor_directive_rejected(self):
        # `#include <stdio.h>` must be impossible to slip in. The
        # tokeniser will see `#` as part of the preceding token and
        # the entire line will fail the let/return regex match.
        t = CTranspiler()
        with pytest.raises(ValueError, match="Unsupported compute DSL"):
            t.transpile(
                "#include <stdio.h>\nreturn x", "Sneaky", ["x"],
            )

    def test_identifier_with_special_chars_sanitised(self):
        # Hyphenated names get sanitised to underscore-separated.
        t = CTranspiler()
        result = t.transpile(
            "return x", "calculate-tax-amount", ["x"],
        )
        assert "axon_compute_calculate_tax_amount" in result.fn_name


# ════════════════════════════════════════════════════════════════════
#  Drift gate — RustTranspiler and CTranspiler accept/reject same DSL
# ════════════════════════════════════════════════════════════════════


class TestDriftGateRustVsC:
    """Founder principle (4 pillars): the two transpilers MUST stay in
    lock-step on what they accept and reject. Adding a feature to one
    requires adding it to the other; if this drift gate fails, the
    invariant has been broken."""

    @pytest.fixture
    def rust(self):
        return RustTranspiler()

    @pytest.fixture
    def c(self):
        return CTranspiler()

    @pytest.mark.parametrize("logic, fn_name, params", [
        ("return a + b", "Add", ["a", "b"]),
        ("return a - b", "Sub", ["a", "b"]),
        ("return a * b", "Mul", ["a", "b"]),
        ("return a / b", "Div", ["a", "b"]),
        ("let x = a + b\nreturn x * 2", "AddMul", ["a", "b"]),
        ("return ( a + b ) * c", "Weighted", ["a", "b", "c"]),
        ("let p = a * a\nlet q = b * b\nreturn p + q", "Norm2", ["a", "b"]),
        ("return 0", "Zero", []),
        ("return 3.14", "Pi", []),
    ])
    def test_both_accept_valid_dsl(self, rust, c, logic, fn_name, params):
        rust_result = rust.transpile(logic, fn_name, params)
        c_result = c.transpile(logic, fn_name, params)
        # Both succeeded; that's the contract.
        assert rust_result.source_hash == c_result.source_hash
        assert rust_result.fn_name == c_result.fn_name
        assert rust_result.param_names == c_result.param_names

    @pytest.mark.parametrize("logic, fn_name, params", [
        ("", "Empty", []),                                # empty body
        ("let x = 1", "NoReturn", []),                    # missing return
        ("return mystery", "Unknown", []),                # unbound ident
        ("return a & b", "Bitwise", ["a", "b"]),         # disallowed op
        ("return sqrt(x)", "Sqrt", ["x"]),               # function call
        ("if a > b: return a", "Conditional", ["a", "b"]),  # control flow
        ("return undeclared", "Undeclared", ["a"]),      # ident not in params
        ("#include <x>\nreturn 1", "Sneaky", []),        # preprocessor
    ])
    def test_both_reject_invalid_dsl(self, rust, c, logic, fn_name, params):
        with pytest.raises(ValueError):
            rust.transpile(logic, fn_name, params)
        with pytest.raises(ValueError):
            c.transpile(logic, fn_name, params)

    def test_operator_whitelist_identical(self, rust, c):
        # Direct invariant check on the class attribute — if anyone
        # adds `%` to one whitelist without the other, this fails.
        assert rust._ALLOWED_OPS == c._ALLOWED_OPS

    def test_fn_name_prefix_identical(self, rust, c):
        # Both must produce `axon_compute_<sanitised_name>`.
        rust_result = rust.transpile("return a", "MyFn", ["a"])
        c_result = c.transpile("return a", "MyFn", ["a"])
        assert rust_result.fn_name == c_result.fn_name == "axon_compute_MyFn"

    def test_sanitisation_identical(self, rust, c):
        rust_result = rust.transpile("return x", "weird-name!", ["x"])
        c_result = c.transpile("return x", "weird-name!", ["x"])
        assert rust_result.fn_name == c_result.fn_name


# ════════════════════════════════════════════════════════════════════
#  NativeCompiler integration — Tier-2 delegation
# ════════════════════════════════════════════════════════════════════


class TestNativeCompilerDelegation:
    """Verify NativeCompiler now uses CTranspiler instead of inline."""

    def test_native_compiler_holds_c_transpiler_instance(self, tmp_path):
        nc = NativeCompiler(cache_dir=tmp_path)
        assert isinstance(nc._c_transpiler, CTranspiler)

    def test_native_compiler_holds_rust_transpiler_instance(self, tmp_path):
        nc = NativeCompiler(cache_dir=tmp_path)
        assert isinstance(nc._transpiler, RustTranspiler)

    def test_inline_transpile_method_removed(self, tmp_path):
        # Regression: pre-25.f the C source was generated by an inline
        # `_transpile_to_c` method on NativeCompiler. After 25.f that
        # method is gone — Tier-2 delegates to CTranspiler. If anyone
        # re-introduces the inline path this test catches it.
        nc = NativeCompiler(cache_dir=tmp_path)
        assert not hasattr(nc, "_transpile_to_c")


# ════════════════════════════════════════════════════════════════════
#  Mathematical-purity boundary (founder ratification 2026-05-08)
# ════════════════════════════════════════════════════════════════════


class TestPurityBoundary:
    """Compute blocks must not be a back door for PIX / MDN / effects.

    The DSL grammar enforces this by construction: only let/return,
    only the four arithmetic operators, only known identifiers. These
    tests assert that the obvious back doors are closed."""

    @pytest.fixture
    def t(self):
        return CTranspiler()

    @pytest.mark.parametrize("forbidden_op", [
        "navigate", "drill", "trail", "recall", "record",
        "perform", "handle", "resume", "abort", "forward",
        "memory", "corpus", "pix",
    ])
    def test_pix_mdn_effects_keywords_rejected_as_identifiers(
        self, t, forbidden_op,
    ):
        # These are not in the param list nor declared as locals, so
        # the transpiler treats them as unknown identifiers and
        # rejects them. The grammar boundary holds even if an adopter
        # accidentally pastes one in.
        with pytest.raises(ValueError, match="Unknown identifier"):
            t.transpile(f"return {forbidden_op}", "Forbidden", [])

    def test_pure_arithmetic_passes_boundary(self, t):
        # The boundary blocks impure stuff; pure morphisms over f64
        # are explicitly the supported case.
        result = t.transpile(
            "let x = a * a\nlet y = b * b\nreturn x + y",
            "Norm2Squared",
            ["a", "b"],
        )
        assert "axon_compute_Norm2Squared" in result.fn_name
