//! § Fase 27.e — Vertical BPE tokenizer templates (Rust shim).
//!
//! Companion to OSS [`axon_csys::tokens`]. Adds three vertical-tuned
//! BPE encoders trained on curated public-domain seed corpora:
//!
//!   - [`medical_base`] — clinical / pharmacological / diagnostic
//!     terminology (ICD-10, SNOMED-CT, FDA Orange Book drug names,
//!     ASR / IDSA guidelines, anatomical nomenclature).
//!   - [`legal_base`] — federal court procedural language, statutory
//!     citations, contract clause boilerplate, Federal Rules of Civil
//!     Procedure, common-law doctrines, securities + IP litigation.
//!   - [`fintech_base`] — SEC EDGAR financial filing terminology,
//!     U.S. GAAP / IFRS accounting standards, FFIEC AML/KYC/BSA,
//!     ECB monetary policy, Basel III capital framework.
//!
//! # Why vertical encoders win
//!
//! The OSS [`axon_csys::cl100k_base`] / [`axon_csys::o200k_base`]
//! encoders were trained on a generic English corpus dominated by
//! Common Crawl + GitHub. Vertical jargon like `myocardial infarction`,
//! `attorney-client privilege`, `know-your-customer due diligence`
//! gets multi-token expansions in those generic encoders — typically
//! 4-7 tokens for a 2-3-word phrase. For Shield judges processing
//! long medical / legal / fintech context, this inflates token cost
//! by 30-50%.
//!
//! A vertical-tuned encoder learns the long jargon as single tokens
//! during BPE training, collapsing those expansions to 1-2 tokens.
//! The result is fewer billable tokens per LLM call AND fewer attention
//! steps per token, both of which compound across an enterprise's
//! request volume.
//!
//! # Encoder versioning
//!
//! v0.1.0 ships **v1 seed** encoders trained on curated public-domain
//! seed corpora embedded in [`tools/train_vertical_merges.py`]. Vocab
//! sizes (with `target_vocab=4096`, `min_pair_freq=1`):
//!
//!   - `medical_v1_seed`: ~2400 tokens (10 KB blob)
//!   - `legal_v1_seed`:   ~1900 tokens ( 8 KB blob)
//!   - `fintech_v1_seed`: ~2000 tokens ( 8 KB blob)
//!
//! These seed encoders are useful for integration testing AND for
//! adopters running on standard vertical-flavoured English text —
//! they collapse the most-frequent jargon into single tokens. For
//! production deployments processing PubMed-Central-scale medical
//! text or full SEC EDGAR filings, adopters retrain via
//! `tools/train_vertical_merges.py --corpus <full-corpus.txt>
//! --vertical <medical|legal|fintech> --target-vocab 32000` and load
//! the resulting `.bin` via [`Tokenizer::from_blob`].
//!
//! # Wire-format compatibility
//!
//! All three vertical encoders use:
//!   - The OSS axon-csys 0.1.x merges blob format (consumed by the
//!     same C BPE engine — drift-gate verified).
//!   - The cl100k_base pretokenizer regex pattern (vertical text
//!     follows English text patterns; reusing cl100k preserves
//!     pretokenizer semantics).
//!   - No special tokens by default. Adopters who feed
//!     `<|endoftext|>`-style markers can layer a special-token
//!     vocabulary at construction time.
//!
//! Encoders are process-scoped — first call to `medical_base()` /
//! `legal_base()` / `fintech_base()` constructs the encoder; subsequent
//! calls reuse the cached handle. Construction is cheap (~1 ms on
//! contemporary hardware for the seed-scale encoders).

use std::sync::OnceLock;

pub use axon_csys::{BpeError, Tokenizer};

// ──────────────────────────────────────────────────────────────────────
// Embedded merges blobs — generated by `tools/train_vertical_merges.py`.
// `include_bytes!` gives a `'static` slice that the C BPE engine can
// borrow zero-copy.
// ──────────────────────────────────────────────────────────────────────

const MERGES_MEDICAL_V1_SEED: &[u8] = include_bytes!("../c-src/tokens/merges_medical_v1_seed.bin");
const MERGES_LEGAL_V1_SEED: &[u8] = include_bytes!("../c-src/tokens/merges_legal_v1_seed.bin");
const MERGES_FINTECH_V1_SEED: &[u8] = include_bytes!("../c-src/tokens/merges_fintech_v1_seed.bin");

// Same pretokenizer regex OSS axon-csys uses for `cl100k_base`. Lifted
// verbatim so the vertical encoders share the OSS pretokenizer semantics.
// (Vertical text is English-flavoured — there's no benefit to a
// vertical-specific pretokenizer pattern, and a divergent pattern would
// break drift-gate parity vs cl100k_base on shared inputs.)
const PAT_CL100K: &str = "'(?i:[sdmt]|ll|ve|re)|[^\\r\\n\\p{L}\\p{N}]?+\\p{L}++|\\p{N}{1,3}+| \
     ?[^\\s\\p{L}\\p{N}]++[\\r\\n]*+|\\s++$|\\s*[\\r\\n]|\\s+(?!\\S)|\\s";

// ──────────────────────────────────────────────────────────────────────
// Public surface — process-scoped tokenizer accessors
// ──────────────────────────────────────────────────────────────────────

/// Stable identifier for the active vertical encoder revision. v0.1.0
/// ships `v1_seed` revisions trained on curated public-domain seed
/// corpora; future releases ship full-corpus retrains under
/// `v1`, `v2`, etc. The identifier is suitable for audit-log emission
/// alongside [`crate::FipsBackend::label`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VerticalEncoderRevision {
    /// `medical_v1_seed` — curated clinical seed corpus (~1100 tokens).
    MedicalV1Seed,
    /// `legal_v1_seed` — curated legal seed corpus (~1050 tokens).
    LegalV1Seed,
    /// `fintech_v1_seed` — curated fintech seed corpus (~1080 tokens).
    FintechV1Seed,
}

impl VerticalEncoderRevision {
    /// Stable string label for audit-log emission. Fixed across
    /// releases of v0.1.x; v0.2.x revs introduce additional variants.
    pub const fn label(self) -> &'static str {
        match self {
            Self::MedicalV1Seed => "medical_v1_seed",
            Self::LegalV1Seed => "legal_v1_seed",
            Self::FintechV1Seed => "fintech_v1_seed",
        }
    }
}

/// Process-scoped medical-vertical tokenizer. First call constructs;
/// subsequent calls return the cached `'static` reference.
///
/// Trained on the curated clinical seed corpus embedded in
/// [`tools/train_vertical_merges.py`]: ICD-10, SNOMED-CT, common
/// medications (FDA Orange Book), anatomical nomenclature, lab test
/// names, IDSA / KDIGO / NIH guidelines language.
pub fn medical_base() -> Result<&'static Tokenizer, BpeError> {
    static CELL: OnceLock<Result<Tokenizer, BpeError>> = OnceLock::new();
    CELL.get_or_init(|| Tokenizer::from_blob(MERGES_MEDICAL_V1_SEED, PAT_CL100K, vec![]))
        .as_ref()
        .map_err(Clone::clone)
}

/// Process-scoped legal-vertical tokenizer.
///
/// Trained on the curated legal seed corpus: federal court procedural
/// language, FRCP / FRE / FRAP rules, statutory + case citations
/// (28 U.S.C., 18 U.S.C., 17 U.S.C., FED. R. CIV. P., etc.), contract
/// clause boilerplate, securities + IP litigation vocabulary.
pub fn legal_base() -> Result<&'static Tokenizer, BpeError> {
    static CELL: OnceLock<Result<Tokenizer, BpeError>> = OnceLock::new();
    CELL.get_or_init(|| Tokenizer::from_blob(MERGES_LEGAL_V1_SEED, PAT_CL100K, vec![]))
        .as_ref()
        .map_err(Clone::clone)
}

/// Process-scoped fintech-vertical tokenizer.
///
/// Trained on the curated financial seed corpus: SEC EDGAR filing
/// terminology (10-K / 10-Q / 8-K / 14A), U.S. GAAP / IFRS accounting
/// standards (ASC 606 / 842 / 350 / 360 / 820 / 815 / 740 / 718 /
/// 260 / 280), FFIEC bank exam vocabulary, BSA / KYC / AML / SOX
/// compliance, Basel III + Dodd-Frank + MiFID frameworks.
pub fn fintech_base() -> Result<&'static Tokenizer, BpeError> {
    static CELL: OnceLock<Result<Tokenizer, BpeError>> = OnceLock::new();
    CELL.get_or_init(|| Tokenizer::from_blob(MERGES_FINTECH_V1_SEED, PAT_CL100K, vec![]))
        .as_ref()
        .map_err(Clone::clone)
}

// ──────────────────────────────────────────────────────────────────────
// Registration surface for ensemble factories
//
// `axon_enterprise.shield.ensemble_configs.healthcare_ensemble()` /
// `legal_ensemble()` / `fintech_ensemble()` (Python side) detect
// whether the enterprise crate is loaded and pick up the vertical
// encoders automatically (per D9 backward-compat). The Rust side
// surfaces the registration via [`available_vertical_encoders`] and
// [`vertical_encoder_for`] so adopters writing dispatch logic in
// Rust can fan out the same way.
// ──────────────────────────────────────────────────────────────────────

/// All vertical encoder revisions shipped in v0.1.0. Useful for
/// adopter dispatch tables that want to enumerate the available
/// vertical-tuned encoders without hard-coding the names.
pub fn available_vertical_encoders() -> &'static [VerticalEncoderRevision] {
    &[
        VerticalEncoderRevision::MedicalV1Seed,
        VerticalEncoderRevision::LegalV1Seed,
        VerticalEncoderRevision::FintechV1Seed,
    ]
}

/// Look up a vertical encoder by revision. Returns the same cached
/// reference as the per-revision accessors above.
pub fn vertical_encoder_for(
    revision: VerticalEncoderRevision,
) -> Result<&'static Tokenizer, BpeError> {
    match revision {
        VerticalEncoderRevision::MedicalV1Seed => medical_base(),
        VerticalEncoderRevision::LegalV1Seed => legal_base(),
        VerticalEncoderRevision::FintechV1Seed => fintech_base(),
    }
}

/// Dispatch by short name string — the labels match
/// [`VerticalEncoderRevision::label`]. Adopter ensemble factories
/// receive the vertical name as a string at config time and use this
/// to resolve the encoder. Returns `None` if the name does not match
/// any v0.1.0 revision.
pub fn vertical_encoder_by_name(name: &str) -> Option<Result<&'static Tokenizer, BpeError>> {
    let rev = match name {
        "medical_v1_seed" | "medical_base" | "medical" => VerticalEncoderRevision::MedicalV1Seed,
        "legal_v1_seed" | "legal_base" | "legal" => VerticalEncoderRevision::LegalV1Seed,
        "fintech_v1_seed" | "fintech_base" | "fintech" => VerticalEncoderRevision::FintechV1Seed,
        _ => return None,
    };
    Some(vertical_encoder_for(rev))
}
